server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: oauth2-client-app
            client-name: oauth2-client-app
            client-secret: lygPKsTF849lHc0PA0uV3HVdGmneGaMU
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            scope: profile,email

          google:
            client-id: 871175160830-jj1ldkrt6sf9v4t2nts58c8tb5dt2ptt.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email

          naver:
            client-id: fwz3GEBWmCQsThk1hnkq
            client-secret: saqe7gWGGa
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile,email
        #                        scope: openid,profile,email

        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/oauth2
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mvc:
    static-path-pattern: /static/**