  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/spring_cloud?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8 # MySQL 호스트와 포트, 데이터베이스 이름을 설정합니다.
      username: root  # MySQL 사용자 이름을 설정합니다.
      password: password  # MySQL 비밀번호를 설정합니다.
    jpa:
      hibernate:
        ddl-auto: update  # Hibernate 자동 생성 설정을 지정합니다.
      show-sql: true  # SQL 쿼리를 로그에 출력할지 여부를 설정합니다.